#!/bin/sh
# prerm script for cosmic-store

set -e

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ] ; then
	update-alternatives --remove gstreamer-codec-install \
			    /usr/bin/cosmic-store || true

fi

#DEBHELPER#

exit 0

