name: Continuous Integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
      - name: Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
          rustflags: ""
      - name: Format
        run: cargo fmt --all -- --check

  clippy-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
      - name: Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
          rustflags: ""
      - name: System dependencies
        run: sudo apt-get update; sudo apt-get install pkg-config libflatpak-dev libssl-dev libxkbcommon-dev libwayland-dev
      - name: Clippy
        run: cargo clippy --workspace --all-features --all-targets -- -D warnings

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
      - name: Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""
      - name: System dependencies
        run: sudo apt-get update; sudo apt-get install pkg-config libflatpak-dev libssl-dev libxkbcommon-dev libwayland-dev
      - name: Test
        run: cargo test --workspace --all-features
